apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sadra/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-cip-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cip-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: atuh
      protocol: TCP
      port: 3000
      targetPort: 3000
