apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: sadra/tickets
          env:
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-cip-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-cip-srv
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: atuh
      protocol: TCP
      port: 3000
      targetPort: 3000
